---
title: "Monte Carlo Integration"
author: "Gifty Osei"
date: "2024-09-12"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Monte Carlo Integration 
Using to approximate integrals that are complication and the close form solution is unattainable.

## Example 1

```{r, warning=FALSE, message=FALSE}
h=function(x){(cos(50*x)+sin(20*x))^2}

par(mar=c(2,2,2,1),mfrow=c(2,1))

curve(h,xlab="Function",ylab="",lwd=2)

print(integrate(h,0,1))

x=h(runif(10^4))

estint=cumsum(x)/(1:10^4)

esterr=sqrt(cumsum((x-estint)^2))/(1:10^4)

plot(estint, xlab="Mean and error range",type="l",lwd=2,
ylim=mean(x)+20*c(-esterr[10^4],esterr[10^4]),ylab="")
lines(estint+2*esterr,col="gold",lwd=2)
lines(estint-2*esterr,col="gold",lwd=2)
```

## Standard Normal CDF

```{r}
x <- seq (.1, 2.5, length=10)
m <- 10000
u <- runif(m)
cdf <- numeric(length(x))
for (i in 1:length(x)){
g <- x[i]*exp(-(u*x[i])^2/2)
cdf[i]<-mean(g)/sqrt(2*pi)+0.5
}
Phi <- pnorm(x)
print(round(rbind(x,cdf,Phi),3))
```


```{r}

m<-10000
theta.hat<-se<-rep(0,4)
h<-function(x){
exp(-x-log(1+x^2))*(x>0)*(x<1)
}
x<-runif(m) # using g0
hg <- h(x)
theta.hat[1]<-mean(hg)
se[1]<-sd(hg)
x<-rexp(m,1) # using g1
hg <- h(x)/exp(-x)
theta.hat[2]<-mean(hg)
se[2]<-sd(hg)
x<-rcauchy(m,1) # using g2
i <- c(which(x>1),which(x<0))
x[i]<-2
hg <- h(x)/dcauchy(x)
theta.hat[3]<-mean(hg)
se[3]<-sd(hg)


u<-runif(m) # using g3, inverse cdf approach
x<- -log(1-u*(1-exp(-1)))
hg <- h(x)/(exp(-x)/(1-exp(-1)))
theta.hat[4]<-mean(hg)
se[4]<-sd(hg)
rbind(theta.hat,se)

```

## Antithetic Variable
```{r}
## Example 1

N = 1000
g = function(t) {log(1+log(1-t)^2)}
T = runif(N); X = g(T)
c(mean(X), sd(X))
## [1] 0.6456271 0.7345544
T = runif(N/2)
X = (g(T) + g(1-T))/2;c(mean(X), sd(X))


## Example 2
N = 1000; U = matrix(runif(2*N),ncol=2)
f = function(x){prod(x)^2*sin(sum(x))*log(sum(x))}
X = pi^2*apply(pi*U/4,1,f)/16
c(mean(X), sd(X))
## [1] 0.003939554 0.012559836
U = matrix(runif(N),ncol=2)
X = pi^2*((apply(pi*U/4,1,f)+apply(pi*(1-U)/4,1,f))/2)/16
c(mean(X), sd(X))
```


## Control Variates

```{r}
## Example 1
N = 1000; U = runif(N); X = exp(U);
c(mean(X), sd(X), 2*sd(X)/sqrt(N))
## [1] 1.71381259 0.48303059 0.03054954
Y = U; muY = 1/2; Xb = mean(X); Yb = mean(Y);
cs = -sum( (X-Xb)*(Y-Yb) )/sum( (Y-Yb)^2 );
Z = X + cs*( Y - muY );
c(mean(Z), sd(Z), 2*sd(Z)/sqrt(N))

## Example 2

N = 1000; U = runif(N); X = 2*exp(-(2*U)^2);
c(mean(X), sd(X), 2*sd(X)/sqrt(N))
## [1] 0.85427898 0.68687148 0.04344157
Y = 2*exp(-2*U); muY = 1 - exp(-2);
Xb = mean(X); Yb = mean(Y);
cs = -sum( (X-Xb)*(Y-Yb) )/sum( (Y-Yb)^2 );
Z = X + cs*( Y - muY );
c(mean(Z), sd(Z), 2*sd(Z)/sqrt(N))


## Example 3
N = 1000; U = matrix(runif(2*N),ncol=2)
f = function(x){prod(x)^2*sin(sum(x))*log(sum(x))}
X = pi^2*apply(pi*U/4,1,f)/16; Xb=mean(X)
c(mean(X), sd(X), 2*sd(X)/sqrt(N))
## [1] 0.004319502 0.013949818 0.000882264
g = function(x) { prod(x)^2 }
Y = pi^2*apply(pi*U/4,1,g)/16; Yb = mean(Y)
cs = -sum( (X-Xb)*(Y-Yb) )/sum( (Y-Yb)^2 );
muY = (pi/4)^6/9; Z = X + cs*( Y - muY );
c(mean(Z), sd(Z), 2*sd(Z)/sqrt(N))
```

## Asian Stock Price
```{r}
S0 = 50; K = 50; M = 16; T = 1; dlt = T/M;
r = 0.05; s = 0.1; rd = ( r - s^2/2 )*dlt;
N = 10000; Z = matrix(rnorm(M*N),ncol=M);
S = matrix(0,ncol=M,nrow=N)
X = Y = rep(0,N)
d = ( log(S0/K) + (r+s^2/6)*T/2 )/(s*sqrt(T/3));
for (j in 1:N){
S[j,] = S0*exp(cumsum(rd + s*sqrt(dlt)*Z[j,]))
X[j] = exp(-r*T)*max( mean(S[j,])-K, 0 );
Y[j] = exp(-r*T)*max((S0*prod(S[j,]))^(1/(M+1))-K,0);
}
c(mean(X), sd(X), 2*sd(X)/sqrt(N))



Xb = mean(X); Yb = mean(Y);
cs = -sum( (X-Xb)*(Y-Yb) )/sum( (Y-Yb)^2 );
muY = exp(-r*T)*(S0*exp((r-s^2/6)*T/2)*pnorm(d)-K*pnorm(d-s*sqrt(T/3)) );
Z = X + cs*( Y - muY );
c(mean(Z), sd(Z), 2*sd(Z)/sqrt(N))
```


